### PR TITLE
standardized the api of repositories

### PR DESCRIPTION
**Pull request by will3216**
Standardized the api for repositories, so that you can use the same methods to read features across all repositories, and add/update/delete features across all dynamic repositories

All repositories now respond to:
* repo#active_features => [Array<Symbol>] all active features
* repo#inactive_features => [Array<Symbol>] all inactive features
* repo#list_features => [Array<Symbol>] all features
* repo#get_feature(<Symbol> feature_name) => true || false depending on if feature is active

All dynamic repositories now respond to:
* repo#add_active_feature(<Symbol> feature_name) => true || false (successfully added)
* repo#add_inactive_feature(<Symbol> feature_name) => true || false (successfully added)
* repo#remove_feature(<Symbol> feature_name) => true || false (successfully removed)
* repo#create_feature(<Symbol> feature_name, <Boolean> active) => true || false (successfully added)
* repo#set_feature(<Symbol> feature_name, <Boolean> active) => true || false (successfully updated)

RedisRepository:
* Added the ability to set custom redis client

ActiveRecordRepository:
* Fixed the call to 'exists?' to make the call against 'name' instead of the default 'id'

### CODE REVIEW

**Comment by javidjamae** [comment]
@will3216 - I feel like you're introducing too many convenience methods and it's making the API more complex than it needs to be. It seems like "create", "set", and "add" are all really just the same thing. Maybe there should just be a "set" and it will find or create (if missing) and then set the value. 

Suggestions:

- Rename repo#list_features to repo#features (to follow ruby conventions)
- Make repo#create default to false for the value argument
- Delete repo#add_active_feature - people can just use repo#create(feature_name, true)
- Delete repo#add_inactive_feature - people can just use repo#create(feature_name)
- Merge repo#set_feature and repo#create_feature - make them a single method that just finds or creates the feature (if missing) and then sets the value
- Delete Feature.set - people can just use Feature.add and it will just call the merged repo#set_feature above

**Comment by will3216** [comment]
@javidjamae I have changed the name of repo#list_feature => repo#features and removed repo#add_inactive_feature (which I only added to match repo#add_active_feature).

The other suggested changes require breaking existing functionality:
* repo#add_active_feature => part of the existing api
* repo#create_feature => currently fails if feature is already in the list and couldn't if it was merged with set_feature

However, I was thinking the same thing to be honest.

**Comment by will3216** [comment]
Hey @mgsnova , so I am realizing this is a lot of changes for one PR. If you'd like, I can close this pull request and replace it with several smaller ones, but I'd like to hear your thoughts before I do that. Thanks!

**Comment by mgsnova** [comment]
I need some more time to have a look on this one.

**Comment by mgsnova** [comment]
Hi,

sorry for the delay, but I was busy lately.

I think this one PR handles to much change and should be separated into several PR's (especially fixes).

I think, having a standardized API for the repos is a good thing. Speaking of API, I see the Feature class a the 'user'-facing API wihtin an application. So this class should only contain functionality for initial configuration (setting a repo, refresh) and feature queries (active?, ...).
The configuration of single features should be done via the repositories. This way it is easy to distinguish between read and write access and the separation of concerns more clear in my eyes.

**Comment by will3216** [comment]
Cool, thanks for the feedback. I'll look into splitting this up in the next few days.

**Comment by mgsnova** [comment]
Please reopen/create new PR if you want to contribute. Thanks

**Comment by will3216** [comment]
Oops, I completely forgot about this, I will try to get to it next week.

**Comment by mgsnova** [comment]
No problem!

**Comment by will3216** [comment]
Hey, now that the tangential changes have been accepted, can we re-open this pull request? I'd rather not go through the work of breaking the rest of the work in here down further if its not necessary. Though, if you aren't okay with that, I can break this up into two parts:
1. Set up the API that will be used for all repos (static or dynamic)
2. Set up the API that will be used for only dynamic repos

**Pull request closed without merging**
